version: '3.9'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: ./packages/api/Dockerfile.dev
    init: true
    volumes:
      - type: bind
        source: ./packages/api
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    networks:
      - development
    ports:
      - 3000:3000
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./packages/client/Dockerfile.dev
    init: true
    volumes:
      - type: bind
        source: ./packages/client
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./packages/client/vite.config.ts
        target: /usr/src/app/vite.config.ts
    networks:
      - development
    ports:
      - 5173:5173

networks:
  development:
